export const AUTH_ERROR_CODES = {
  // Reset password errors
  INVALID_RESET_TOKEN: "INVALID_RESET_TOKEN",
  RESET_TOKEN_EXPIRED: "RESET_PASSWORD_EXPIRED",
  RESET_TOKEN_USED: "RESET_TOKEN_USED",
  SAME_PASSWORD: "SAME_PASSWORD",

  // OTP errors
  INVALID_OTP: "INVALID_OTP",
  OTP_EXPIRED: "OTP_EXPIRED",

  // Account errors
  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",
  ACCOUNT_ALREADY_ACTIVE: "ACCOUNT_ALREADY_ACTIVE",
} as const;

export const RESET_TOKEN_INVALID_CODES: string[] = [
  AUTH_ERROR_CODES.INVALID_RESET_TOKEN,
  AUTH_ERROR_CODES.RESET_TOKEN_EXPIRED,
  AUTH_ERROR_CODES.RESET_TOKEN_USED,
];